language: python
python:
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
before_install:
  - pip install -U pip
install:
  - pip install .[dev]
before_script:
  - flake8 .
script:
  - python setup.py nosetests
after_script:
  - pip install codecov
  - codecov
